Repository elastic/golang-crossbuild, pull requests merged in 2020-07, with the labels that each got.

#58 Add dependencies for x-pack/auditbeat and Journalbeat
  go1.13/arm/Dockerfile.tmpl
  go1.13/base/Dockerfile.tmpl
  go1.13/main/Dockerfile.tmpl
  go1.13/mips/Dockerfile.tmpl
  go1.13/ppc/Dockerfile.tmpl
  go1.13/s390x/Dockerfile.tmpl
  go1.14/arm/Dockerfile.tmpl
  go1.14/mips/Dockerfile.tmpl
  go1.14/ppc/Dockerfile.tmpl
  go1.14/s390x/Dockerfile.tmpl
Labels: Team:Automation, automation, enhancement

#57 Add support to create debian9 images
  Makefile
  go1.10/Makefile.debian9
  go1.11/Makefile.debian9
  go1.12/Makefile.debian9
  go1.13/Makefile.debian9
  go1.14/Makefile.debian9
Labels: [zube]: In Review, review

#59 fix: user the same version tag than Go in Beats
  go1.13/Makefile.common
Labels: Team:Automation, automation, bug

#61 fix: set the proper sha256
  go1.13/base/Dockerfile.tmpl
Labels: Team:Automation, automation, bug

#64 fix: bump go version to 1.14.6
  go1.14/Makefile.common
  go1.14/base/Dockerfile.tmpl
Labels: Team:Automation, automation, enhancement
