Repository elastic/golang-crossbuild, pull requests merged in 2021-06, with the labels that each got.

#106 Update patch version of golang
  go1.15/base-arm/Dockerfile.tmpl
  go1.15/base/Dockerfile.tmpl
  go1.16/base-arm/Dockerfile.tmpl
  go1.16/base/Dockerfile.tmpl
Labels: Team:Agent

#108 Bump golang version with the latest supported one
  .ci/bump-go-release-version.sh
  .gitignore
  .mergify.yml
Labels: automation

#111 Support arm64 and amd64 sha validations
  .ci/bump-go-release-version.sh
Labels: Team:Automation, automation
