Repository elastic/golang-crossbuild, pull requests merged in 2021-10, with the labels that each got.

#124 [docs] update supported golang versions and docker tags
  README.md
Labels: Team:Automation

#125 go1.15 EOL - Go 1.5 was supported until the Go 1.7 release
  Jenkinsfile
  Makefile
  go1.15/Makefile
  go1.15/Makefile.common
  go1.15/Makefile.debian10
  go1.15/Makefile.debian7
  go1.15/Makefile.debian8
  go1.15/Makefile.debian9
  go1.15/arm/.dockerignore
  go1.15/arm/Dockerfile.tmpl
  go1.15/arm/Makefile
  go1.15/arm/rootfs/compilers.yaml
  go1.15/arm/rootfs/helloWorld.c
  go1.15/armel/.dockerignore
  go1.15/armel/Dockerfile.tmpl
  go1.15/armel/Makefile
  go1.15/armel/rootfs/compilers.yaml
  go1.15/armel/rootfs/helloWorld.c
  go1.15/armhf/.dockerignore
  go1.15/armhf/Dockerfile.tmpl
  go1.15/armhf/Makefile
  go1.15/armhf/rootfs/compilers.yaml
  go1.15/armhf/rootfs/helloWorld.c
  go1.15/base-arm/Dockerfile.tmpl
  go1.15/base-arm/Makefile
  go1.15/base-arm/rootfs/entrypoint.go
  go1.15/base-arm/sources-debian9.list
  go1.15/base/.dockerignore
  go1.15/base/Dockerfile.tmpl
  go1.15/base/Makefile
  go1.15/base/rootfs/entrypoint.go
  go1.15/base/sources-debian10.list
  go1.15/base/sources-debian7.list
  go1.15/base/sources-debian8.list
  go1.15/base/sources-debian9.list
  go1.15/darwin/Dockerfile.tmpl
  go1.15/darwin/Makefile
  go1.15/darwin/rootfs/compilers.yaml
  go1.15/darwin/rootfs/helloWorld.c
  go1.15/main/.dockerignore
  go1.15/main/Dockerfile.tmpl
  go1.15/main/Makefile
  go1.15/main/rootfs/compilers.yaml
  go1.15/main/rootfs/helloWorld.c
  go1.15/mips/.dockerignore
  go1.15/mips/Dockerfile.tmpl
  go1.15/mips/Makefile
  go1.15/mips/rootfs/compilers.yaml
  go1.15/mips/rootfs/helloWorld.c
  go1.15/ppc/.dockerignore
  go1.15/ppc/Dockerfile.tmpl
  go1.15/ppc/Makefile
  go1.15/ppc/rootfs/compilers.yaml
  go1.15/ppc/rootfs/helloWorld.c
  go1.15/s390x/.dockerignore
  go1.15/s390x/Dockerfile.tmpl
  go1.15/s390x/Makefile
  go1.15/s390x/rootfs/compilers.yaml
  go1.15/s390x/rootfs/helloWorld.c
Labels: automation

#126 CI: allow caching to rebuild if needed
  Jenkinsfile
Labels: automation

#129 internal: use google storage bucket for WpdPack_4_1_2.zip
  go1.16/main/Dockerfile.tmpl
  go1.17/main/Dockerfile.tmpl
Labels: automation, Team:Automation

#128 [automation] Update go release version 1.17.2
  Jenkinsfile
  go1.17/Makefile.common
  go1.17/base-arm/Dockerfile.tmpl
  go1.17/base/Dockerfile.tmpl
Labels: automation, dependency
