Repository elastic/golang-crossbuild, pull requests merged in 2021-11, with the labels that each got.

#131 release: automate changelog generation
  .ci/scripts/release-notes.sh
  .grenrc.js
  Jenkinsfile
  README.md
Labels: automation

#134 fix missing deps for librpmio3 and post-release stage in the pipeline
  Jenkinsfile
  go1.16/mips/Dockerfile.tmpl
  go1.16/mips32/Dockerfile.tmpl
  go1.16/ppc/Dockerfile.tmpl
  go1.16/s390x/Dockerfile.tmpl
  go1.17/mips/Dockerfile.tmpl
  go1.17/mips32/Dockerfile.tmpl
  go1.17/ppc/Dockerfile.tmpl
  go1.17/s390x/Dockerfile.tmpl
Labels: automation

#135 [Automation] Update go release version to 1.16.9
  Jenkinsfile
  go1.16/Makefile.common
  go1.16/base-arm/Dockerfile.tmpl
  go1.16/base/Dockerfile.tmpl
Labels: automation, Team:Automation

#137 Release: enable gren in the PATH and bump go version
  .ci/scripts/gren
  Jenkinsfile
Labels: bug

#138 [automation] Update go release version 1.17.3
  Jenkinsfile
  go1.17/Makefile.common
  go1.17/base-arm/Dockerfile.tmpl
  go1.17/base/Dockerfile.tmpl
Labels: automation, dependency
