Repository elastic/golang-crossbuild, pull requests merged in 2022-09, with the labels that each got.

#227 Add debian11 to the release notes
  .grenrc.js
  README.md
Labels: automation, backport-skip

#226 mergify: add support for 1.18 backports
  .mergify.yml
Labels: backport-skip

#234 [automation] Update go release version 1.18.6
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency

#233 [automation] Update go release version 1.19.1
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency, backport-skip

#235 fix: support major.minor in addition to major.minor.patch
  .ci/bump-go-release-version.sh
Labels: backport-v1.18

#237 docs: access to the google storage bucket
  NPCAP.md
Labels: backport-skip

#236 bump npcap version to 1.71
  Makefile.common
Labels: backport-skip

#239 docs: add note to make sure back ports are added
  NPCAP.md
Labels: backport-skip
