Repository elastic/golang-crossbuild, pull requests merged in 2022-03, with the labels that each got.

#161 [automation] Update go release version 1.17.8
  Jenkinsfile
  go1.17/Makefile.common
  go1.17/base-arm/Dockerfile.tmpl
  go1.17/base/Dockerfile.tmpl
Labels: automation, dependency

#162 ci: release for 1.x branches
  Jenkinsfile
Labels: backport-skip

#165 [automation] Update go release version 1.17.8
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: automation, dependency

#166 [automation] Update go release version 1.18
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: automation, dependency, backport-skip
