Repository elastic/golang-crossbuild, pull requests merged in 2022-10, with the labels that each got.

#242 [automation] Update go release version 1.18.7
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency

#241 [automation] Update go release version 1.19.2
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency, backport-skip

#240 action: use release drafter for the release generation when a git tag release is created
  .ci/scripts/gren
  .ci/scripts/release-notes.sh
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .gitignore
  .grenrc.js
  Jenkinsfile
Labels: backport-skip
