Repository elastic/golang-crossbuild, pull requests merged in 2022-11, with the labels that each got.

#246 fix libc6-dev : Depends: libc6 (= 2.31-13+deb11u4) but 2.31-13+deb11u5
  go/base/Dockerfile.tmpl
Labels: bug, backport-v1.18

#244 [automation] Update go release version 1.19.3
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency, backport-skip

#243 [automation] Update go release version 1.18.8
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency
