Repository elastic/golang-crossbuild, pull requests merged in 2022-05, with the labels that each got.

#192 chore: remove Go version from the LLVM image tag
  .ci/llvm-apple.groovy
  go/llvm-apple/Makefile
Labels: backport-skip

#195 fix: remove echo from the push command
  go/llvm-apple/Makefile
Labels: bug, Team:Automation, backport-skip

#196 chore: trim if in templates
  go/arm/Dockerfile.tmpl
  go/armel/Dockerfile.tmpl
  go/armhf/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin/Dockerfile.tmpl
  go/main/Dockerfile.tmpl
  go/mips/Dockerfile.tmpl
  go/mips32/Dockerfile.tmpl
  go/ppc/Dockerfile.tmpl
  go/s390x/Dockerfile.tmpl
Labels: enhancement, Team:Automation, backport-skip

#103 feat: support for darwin/arm64e
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin/Dockerfile.tmpl
Labels: enhancement, backport-skip

#203 [automation] Update go release version 1.17.10
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: automation, dependency

#198 fix: stage FPM images on PRs
  .ci/fpm.groovy
Labels: bug, Team:Automation, backport-skip

#194 feat: add binutils-mutiarch
  go/base/Dockerfile.tmpl
Labels: enhancement, Team:Automation, backport-skip

#197 feat: build multiarch Docker images
  .ci/scripts/buildx.sh
  Jenkinsfile
  Makefile.common
  go/Makefile.common
  go/base/Dockerfile.tmpl
  go/base/Makefile
  go/base/install-go.sh
Labels: enhancement, Team:Automation, backport-skip

#201 feat: build arm64 Docker image for amd64/arm64
  .ci/scripts/buildx.sh
  go/arm/Dockerfile.tmpl
  go/arm/Makefile
  go/base/Makefile
Labels: enhancement, Team:Automation, backport-skip

#204 fix auto-bump
  .ci/bump-go-release-version.sh
  go/base/install-go.sh
Labels: automation, backport-skip

#202 [automation] Update go release version 1.18.2
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency, backport-skip

#199 feat: build amd64/arm64 LLVM Docker images
  .ci/llvm-apple.groovy
  .ci/scripts/buildx.sh
  go/llvm-apple/Dockerfile.tmpl
  go/llvm-apple/Makefile
  go/llvm-apple/lcxx.patch
Labels: enhancement, Team:Automation, backport-skip

#205 chore: set timeout for the LLVM Apple job
  .ci/llvm-apple.groovy
Labels: Team:Automation, backport-skip

#200 feat: build darwin amd64/arm64 Docker images
  .gitignore
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin-arm64/Makefile
  go/darwin/Dockerfile.tmpl
  go/darwin/Makefile
Labels: enhancement, Team:Automation, backport-skip
