Repository elastic/golang-crossbuild, pull requests merged in 2022-04, with the labels that each got.

#175 fix: remove support for debian 9 on mips mips32 ppc s390x
  go/Makefile
  go/Makefile.debian9
Labels: bug, Team:Automation, backport-v7.17

#172 [automation] Update go release version 1.18.1
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: automation, dependency, backport-skip

#171 [automation] Update go release version 1.17.9
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: automation, dependency

#179 docs: debian 10 support only for some platforms
  README.md
Labels: backport-skip

#183 feat: job to build/push fpm docker images
  .ci/fpm.groovy
  .ci/jobs/fpm-mbp.yml
Labels: enhancement, Team:Automation, backport-skip

#182 feat: job to compile the LLVM Apple version
  .ci/jobs/folders.yml
  .ci/jobs/llvm-apple-mbp.yml
  .ci/llvm-apple.groovy
  go/llvm-apple/Dockerfile.tmpl
  go/llvm-apple/Makefile
Labels: enhancement, Team:Automation, backport-skip

#185 fix: typo
  .ci/fpm.groovy
  .ci/llvm-apple.groovy
Labels: bug, Team:Automation

#186 chore: disable default PR notifications
  .ci/jobs/fpm-mbp.yml
  .ci/jobs/llvm-apple-mbp.yml
Labels: Team:Automation, backport-skip

#187 fix: move header to the first line
  .ci/jobs/fpm-mbp.yml
  .ci/jobs/golang-crossbuild-mbp.yml
  .ci/jobs/llvm-apple-mbp.yml
  Jenkinsfile
Labels: bug, Team:Automation, backport-skip

#181 ci: docker image table for generated images
  Jenkinsfile
Labels: backport-skip

#188 fix: add TAG_EXTENSION to use the right base images
  .ci/llvm-apple.groovy
Labels: bug, Team:Automation, backport-skip

#189 fix: Increase timeout
  .ci/fpm.groovy
  .ci/llvm-apple.groovy
Labels: bug, Team:Automation, backport-skip

#180 Support Debian 11
  Jenkinsfile
  Makefile
  go/Makefile.debian11
  go/arm/Dockerfile.tmpl
  go/armel/Dockerfile.tmpl
  go/armhf/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
  go/base/sources-debian11.list
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin/Dockerfile.tmpl
  go/main/Dockerfile.tmpl
  go/mips/Dockerfile.tmpl
  go/mips32/Dockerfile.tmpl
  go/ppc/Dockerfile.tmpl
  go/s390x/Dockerfile.tmpl
Labels: impact:low, backport-v1.17

#193 jjbb: build go version branches (major.minor)
  .ci/jobs/fpm-mbp.yml
  .ci/jobs/golang-crossbuild-mbp.yml
  .ci/jobs/llvm-apple-mbp.yml
Labels: backport-skip
