Repository elastic/golang-crossbuild, pull requests merged in 2023-02, with the labels that each got.

#260 [automation] Update go release version 1.20
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, dependency, backport-skip

#261 mergify: enable 1.19 branch backport
  .mergify.yml
Labels: backport-skip

#262 automate bump golang version
  .ci/bump-go-release-version.sh
  .ci/bump-golang.yml
  .github/workflows/bump-golang-1.18.yml
  .github/workflows/bump-golang-1.19.yml
  .github/workflows/bump-golang.yml
  .github/workflows/bump-golang/action.yml
Labels: automation, backport-v1.18, backport-v1.19

#264 action: fix relative path
  .github/workflows/bump-golang-1.18.yml
  .github/workflows/bump-golang-1.19.yml
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#266 updatecli: use condition to fix shell action idempotence
  .ci/bump-golang.yml
Labels: backport-skip

#270 1.18 is not active
  .github/workflows/bump-golang-1.18.yml
  .github/workflows/opentelemetry.yml
Labels: backport-skip
