Repository elastic/golang-crossbuild, pull requests merged in 2023-12, with the labels that each got.

#360 bump npcap version to 1.78
  Makefile.common
Labels: backport-v1.20

#363 auto-bump: fix permissions
  .buildkite/bump-go-release-version.sh
Labels: backport-v1.20

#365 [Automation] Bump Golang version to 1.21.5
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#366 [Automation] Bump Golang version to 1.20.12
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#368 docs: explain how to update the auto-bump
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
  .github/workflows/opentelemetry.yml
  README.md
Labels: backport-skip
