Repository elastic/golang-crossbuild, pull requests merged in 2023-06, with the labels that each got.

#296 [Automation] Bump Golang version to 1.20.5
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#297 [Automation] Bump Golang version to 1.19.10
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#298 enable Debian 12 and bump llvm version to swift-5.6.3
  .ci/llvm-apple.groovy
  .github/release-drafter.yml
  Jenkinsfile
  Makefile
  README.md
  go/Makefile.debian12
  go/arm/Dockerfile.tmpl
  go/armel/Dockerfile.tmpl
  go/armhf/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
  go/base/sources-debian12.list
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin/Dockerfile.tmpl
  go/llvm-apple/Dockerfile.tmpl
  go/main/Dockerfile.tmpl
  go/mips/Dockerfile.tmpl
  go/mips32/Dockerfile.tmpl
  go/ppc/Dockerfile.tmpl
  go/s390x/Dockerfile.tmpl
Labels: enhancement, backport-v1.19

#302 release notes: add docker image suffixes
  .github/release-drafter.yml
  README.md
Labels: backport-v1.19

#304 docs: remove windows 32 references
  .github/release-drafter.yml
  README.md
Labels: question, backport-v1.19

#280 docs: document development process
  README.md
Labels: backport-skip
