Repository elastic/golang-crossbuild, pull requests merged in 2023-11, with the labels that each got.

#329 Added pipelines for llvm-apple and fpm
  .buildkite/fpm-pipeline.yml
  .buildkite/llvm-apple-pipeline.yml
  catalog-info.yaml
Labels: backport-skip

#326 Migrate golang-crossbuild pipeline
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/pipeline.yml
  .buildkite/scripts/build.sh
  .buildkite/scripts/buildx.sh
  .buildkite/scripts/common.sh
  .buildkite/scripts/post-release.sh
  .buildkite/scripts/publish.sh
  Makefile.common
  catalog-info.yaml
Labels: backport-skip

#331 Updated branch filtering and removed matrix
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: backport-skip

#332 Updated pull-requests.json with llvm-apple & fpm pipelines
  .buildkite/pull-requests.json
Labels: backport-skip

#333 [Automation] Bump Golang version to 1.21.4
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#334 [Automation] Bump Golang version to 1.20.11
  Jenkinsfile
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#335 updatecli: use .go-version
  .buildkite/pipeline.yml
  .buildkite/scripts/common.sh
  .ci/bump-go-release-version.sh
  .ci/bump-golang.yml
  .go-version
  Jenkinsfile
Labels: backport-v1.20

#330 LLVM Apple & FPM pipelines migration
  .buildkite/fpm-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/llvm-apple-pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/changeset/fpm
  .buildkite/scripts/changeset/llvm-apple
  .buildkite/scripts/common.sh
  .buildkite/scripts/llvm-fpm/build.sh
  .buildkite/scripts/llvm-fpm/publish.sh
  .buildkite/scripts/post-release.sh
  catalog-info.yaml
  fpm/Dockerfile.tmpl
Labels: backport-v1.20

#337 Jenkins cleanup: Part 1
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .ci/jobs/folders.yml
  .ci/jobs/fpm-mbp.yml
  .ci/jobs/golang-crossbuild-mbp.yml
  .ci/jobs/llvm-apple-mbp.yml
  .mergify.yml
Labels: backport-v1.20

#348 Updated pre-command script
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
Labels: backport-v1.20

#345 Update .go-version
  .go-version
Labels: backport-skip

#350 Added docker login for release steps
  .buildkite/hooks/pre-command
Labels: backport-v1.20

#352 Updated post-release step key
  .buildkite/hooks/pre-command
Labels: backport-v1.20

#338 Jenkins cleanup - Part 2
  .buildkite/bump-go-release-version.sh
  .buildkite/bump-golang.yml
  .ci/fpm.groovy
  .ci/jobs/defaults.yml
  .ci/llvm-apple.groovy
  .ci/scripts/buildx.sh
  .github/workflows/bump-golang/action.yml
  Jenkinsfile
  README.md
  go/arm/Makefile
  go/base/Makefile
  go/darwin-arm64/Makefile
  go/darwin/Makefile
  go/llvm-apple/Makefile
Labels: backport-v1.20

#357 bk: run for 1.x branches
  catalog-info.yaml
Labels: backport-skip

#358 Add Buildkite build badge
  .buildkite/hooks/pre-exit
  README.md
Labels: backport-v1.20
