Repository elastic/golang-crossbuild, pull requests merged in 2024-02, with the labels that each got.

#382 Change GCS bucket from obs-ci-cache to ingest-buildkite-ci
  Makefile.common
  NPCAP.md
Labels: backport-skip

#388 [Automation] Bump Golang version to 1.21.7
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#389 [Automation] Bump Golang version to 1.20.14
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#391 github-action: listen for all the workflow runs
  .github/workflows/opentelemetry.yml
Labels: backport-skip

#390 automation: support EOL bump automation
  .buildkite/bump-go-release-version.sh
Labels: backport-v1.20
