Repository elastic/golang-crossbuild, pull requests merged in 2024-05, with the labels that each got.

#401 [Automation] Bump Golang version to 1.21.10
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#402 [Automation] Bump Golang version to 1.22.3
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#403 updatecli: enable dependabot, refactor and use signed commits
  .github/actions/bump-golang/action.yml
  .github/dependabot.yml
  .github/updatecli.d/bump-go-release-version.sh
  .github/updatecli.d/bump-golang.yml
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
  README.md
Labels: backport-skip

#406 updatecli: fix location of the file
  .github/actions/bump-golang/action.yml
Labels: backport-skip

#409 mergify: enable backport-v1.21
  .mergify.yml
Labels: backport-skip

#411 github-actions: use github secrets for updatecli
  .github/actions/bump-golang/action.yml
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
Labels: backport-v1.21
