Repository elastic/golang-crossbuild, pull requests merged in 2024-01, with the labels that each got.

#373 [Automation] Bump Golang version to 1.21.6
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#367 ci(action): auto-bump daily and update who notify to
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
Labels: backport-skip

#374 action: honour the right parameters for notifying and fix condition
  .buildkite/bump-golang.yml
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
  .github/workflows/bump-golang/action.yml
Labels: backport-v1.20

#377 [Automation] Bump Golang version to 1.20.13
  .go-version
  go/Makefile.common
  go/base-arm/Dockerfile.tmpl
  go/base/install-go.sh
Labels: automation, backport-skip

#378 Bump npcap version to 1.79
  Makefile.common
Labels: backport-v1.20

#383 Make npcap image build fail if installer is not present
  go/Makefile.common
  go/npcap/Dockerfile.tmpl
Labels: backport-skip

#384 [CI] Abort image building process if the npcap file non found
  Makefile.common
Labels: backport-skip

#386 Corrected GCP credentials
  .buildkite/hooks/pre-command
  .buildkite/pipeline.yml
Labels: backport-v1.20
