Repository elastic/golang-crossbuild, pull requests merged in 2025-03, with the labels that each got.

#524 fix(go/base): set GOTOOLCHAIN=local and skip building arm using the base Dockerfile
  go/Makefile.debian9
  go/base-arm/Dockerfile.tmpl
  go/base-arm/rootfs/entrypoint.go
  go/base/Dockerfile.tmpl
  go/base/rootfs/entrypoint.go
Labels: backport-skip

#532 use tonistiigi/binfmt without a tag
  .buildkite/scripts/buildx.sh
Labels: backport-v1.23

#546 Fix llvm-apple after #531
  .buildkite/llvm-apple-pipeline.yml
  .buildkite/scripts/llvm-apple/build.sh
  .buildkite/scripts/llvm-apple/publish.sh
Labels: backport-skip

#549 Update CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip

#551 Update version in Makefile.common
  go/Makefile.common
Labels: backport-skip

#556 buildkite: support for npcap releases or urgency releases
  .buildkite/pipeline.yml
Labels: backport-v1.23

#533 ci: split debian 11 amd/arm
  .buildkite/pipeline.yml
  Makefile.common
  go/Makefile.debian10
  go/Makefile.debian11
  go/Makefile.debian12
  go/base-arm/Dockerfile.tmpl
  go/base-arm/sources-debian10.list
  go/base-arm/sources-debian11.list
  go/base-arm/sources-debian12.list
  go/base-arm/sources-debian9.list
  go/base/Dockerfile.tmpl
  go/darwin-arm64/Dockerfile.tmpl
  go/darwin-arm64/rootfs/compilers.yaml
  go/darwin/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-v1.23

#528 feat(build): more additions of --progress=plain to docker build
  go/Makefile.common
Labels: Team:Elastic-Agent-Control-Plane, backport

#565 Strip microsoft/go pre-release identifier
  go/base-arm/Dockerfile.tmpl
  go/base/Dockerfile.tmpl
Labels: Team:Elastic-Agent-Control-Plane, backport-skip
