Repository elastic/golang-crossbuild, pull requests merged in 2025-06, with the labels that each got.

#621 Restore debian7 images needed for beats 7.17
  .buildkite/pipeline.yml
  .github/release-drafter.yml
  Makefile
  README.md
  go/Makefile.debian7
Labels: backport-skip

#628 docs: update the list of containers
  .github/release-drafter.yml
Labels: backport-skip

#630 Reintroduce debian8 publishing for go 1.24
  .buildkite/pipeline.yml
  Makefile
  README.md
  go/Makefile.debian8
  go/base-arm/Dockerfile.tmpl
  go/base-arm/sources-debian8.list
Labels: Team:Elastic-Agent-Control-Plane, backport-skip

#631 bk: use docker login plugin
  .buildkite/fpm-pipeline.yml
  .buildkite/hooks/pre-command
  .buildkite/hooks/pre-exit
  .buildkite/llvm-apple-pipeline.yml
  .buildkite/pipeline.yml
  .buildkite/scripts/build.sh
Labels: backport-v1.23

#632 Fix bump MS Golang bump in 1.23
  .github/updatecli.d/bump-go-microsoft-version.sh
  .github/workflows/bump-golang-previous.yml
  .github/workflows/bump-golang.yml
Labels: Team:Elastic-Agent-Control-Plane
